### ISSUE TITLE
404 Error when refreshing on Duck Armageddon

### ISSUE THREAD

**Issue by chadrosser** [norarcasey/norarcasey.github.io#1]
When the dev server starts up after going to the Duck Armageddon page, and you refresh the page then you are met with a 404 error.

**Comment by norarcasey** [comment]
Thanks for letting me know.  I pushed out a fix.  

FWIW the issue stemmed from github pages and react router not working well together with BrowserRouter.
There is a work around that I implemented based on the suggestion from create-react-app.

For more detailed info checkout:
https://create-react-app.dev/docs/deployment/#notes-on-client-side-routing
https://github.com/rafgraph/spa-github-pages
